name: mobileclaw_app
description: PicoClaw core logic mobile port (Go -> Dart)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  file_picker: ^10.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  archive: ^3.6.1
  collection: ^1.19.1
  intl: ^0.19.0
  flutter_foreground_task: ^8.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  archive: ^3.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/default_workspace/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
